# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:35
from __future__ import unicode_literals

import apps.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[apps.login.models.validateLengthGreaterThanTwo, apps.login.models.validateOnlyLetters])),
                ('username', models.CharField(max_length=45, unique=True, validators=[apps.login.models.validateLengthGreaterThanTwo, apps.login.models.validateOnlyLetters])),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
