# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:54
from __future__ import unicode_literals

import apps.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, validators=[apps.login.models.validateLengthGreaterThanTwo, apps.login.models.validateOnlyLetters]),
        ),
    ]
